#! /usr/bin/bash

alias t='trizen --forcecolors'
alias tf='trizen --forcecolors -Ss'
alias ts='trizen --forcecolors -S'
alias tr='trizen --forcecolors -Rc'
alias tc='trizen --forcecolors -Sc'
alias up='trizen --forcecolors -Syu'
