#! /usr/bin/bash

bash_temp=.bash.temp
zsh_temp=.zsh.temp

if [ ! -f ${bash_temp} ]; then
	touch ${bash_temp}
	echo "touch temp file: ${bash_temp}"
fi

if [ ! -f ${zsh_temp} ]; then
	touch ${zsh_temp}
	echo "touch ${zsh_temp}"
fi

cat bashrc > ${bash_temp}
echo "write bashrc into ${bash_temp}"

cat zshrc > ${zsh_temp}
echo "write zshrc into ${zsh_temp}"

alias_config=(`ls alias_*`)

echo "detected alias: $alias_config"

for i in "${alias_config[@]}"; do
	echo "source ${PWD}/${i}" >> ${bash_temp}
	echo "write source ${PWD}/${i} into ${bash_temp}"

	echo "source ${PWD}/${i}" >> ${zsh_temp}
	echo "write source ${PWD}/${i} into ${zsh_temp}"
done


cp -f ${bash_temp} $HOME/.bashrc
echo "cp -f ${bash_temp} ${HOME}/.bashrc"

cp -f ${zsh_temp} ${HOME}/.zshrc
echo "cp -f ${zsh_temp} ${HOME}/.zshrc"

rm ${bash_temp}
rm ${zsh_temp}

cp -f bash_profile ${HOME}/.bash_profile
echo "cp -f bash_profile ${HOME}/.bash_profile"

