#! /usr/bin/bash

build() 
{
    if [ -d "$PWD/build" ] ; then
		echo "cd "$PWD/build""
        cd "$PWD/build"
    else
		echo "mkdir "$PWD/build" && cd "$PWD/build""
        mkdir "$PWD/build" && cd "$PWD/build"
    fi

    if [ -f "../CMakeLists.txt" ] ; then 
		echo "cmake -G Ninja .."
		cmake -G Ninja ..

		echo "ninja"
		ninja

    else if [ -f "../makefile" ] || [ -f "../Makefile" ] || [ -f "../GNUMakefile" ]; then 
		echo "make -j 8 -C .."
		make -j 8 -C ..

    fi fi

    cd ..
}

build
