#!/bin/bash

build() 
{
	# create build directory if not exsit
    if [ -d "$PWD/build" ] ; then
		echo "cd "$PWD/build""
        cd "$PWD/build"
    else
		echo "mkdir "$PWD/build" && cd "$PWD/build""
        mkdir "$PWD/build" && cd "$PWD/build"
    fi

    if [ -f "../CMakeLists.txt" ] ; then 
		case $1 in
			release) 
				echo "set compile type release"
				cmake_flag="-DCMAKE_BUILD_TYPE=Release ${cmake_flag}"
				;;
			re)
				echo "set compile type release"
				cmake_flag="-DCMAKE_BUILD_TYPE=Release ${cmake_flag}"
				;;

			debug)
				echo "set compile type debug"
				cmake_flag="-DCMAKE_BUILD_TYPE=Debug ${cmake_flag}"
				;;
			de)
				echo "set compile type debug"
				cmake_flag="-DCMAKE_BUILD_TYPE=Debug ${cmake_flag}"
				;;
			*)
				echo "unknow type $1"
				;;
		esac

		echo "cmake ${cmake_flag} -G Ninja .."
		cmake ${cmake_flag} -G Ninja ..

		echo "ninja"
		ninja

    else if [ -f "../makefile" ] || [ -f "../Makefile" ] || [ -f "../GNUMakefile" ]; then 
		echo "make -j 8 -C .."
		make -j 8 -C ..

    fi fi

    cd ..
}

build $*
